version: "3"
services:
  oracle:
    image: oracle/database:19.3.0-ee
    container_name: oracle-db-19c-ee
    shm_size: "1gb"
    ports:
      - "5500:5500"
      - "1521:1521"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=password
      - ORACLE_CHARACTERSET=AL32UTF8

